name: Buildozer Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer -v android debug
        workdir: .

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-app-apk
        path: ${{ steps.buildozer.outputs.filename }}
